### PR TITLE
SEO Branding Update

### PR DESCRIPTION
**Pull request by JoshWhelan**
Updates html tags to improve SEO performance.  Reduced keywords and added branding.

### CODE REVIEW

**Comment by whazzmaster** [comment]
:+1:

**Comment by bigtiger** [comment]
I think this is fine. There's a tightrope being walked here. We don't prevent *anyone* from applying/attending. The program is *for* everyone and we're targeting populations underrepresented in tech.

**Comment by JoshWhelan** [comment]
@bigtiger Point taken, but the description mirrors the existing headline - "A web design and development training program in Madison, Wisconsin for women and people of color. A partnership of YWCA Madison and Adorable.io". 

I could work on it a bit more if there's a concern. Vannessa has mentioned that we want to move away from "people of color" as well.

**Comment by bigtiger** [comment]
👍

**Pull request merged**
