### PR TITLE
Update next cohort date

### PR DESCRIPTION
**Pull request by ericanaughton**
@chriscoyier i've updated the date for the next cohort.

### CODE REVIEW

**Comment by rylnd** [comment]
I think that #20 supersedes this, but this brings up a concern about the divergence between the `master` and `gh-pages` branches.

Is `master` even needed any more? @chriscoyier I'm assuming that the work in cad09a726d69689d2984abc720f585245d0dd8c5 is not easily automated/reproducible such that we can have a developer story like:
1. branch off master
1. develop with master's tools 
1. merge back to master
1. generate commit for gh-pages

**Comment by rylnd** [comment]
cc @itsthatguy

**Comment by chriscoyier** [comment]
I was just working off master. It was set up such that `gulp deploy` did the work of getting the necessary stuff onto `gh-pages`. So branching and those steps you laid out seem fine to me.

**Comment by itsthatguy** [comment]
Master is still needed... we should not being doing pull requests directly to gh-pages. As @chriscoyier said, the work needs to be merged into `master`, from which you would use `gulp deploy` to deploy to `gh-pages`

**Comment by itsthatguy** [comment]
@ericanaughton please reissue this PR against master via the instructions here: https://github.com/adorableio/ywebca-site/pull/20#issuecomment-148405085

**Comment by rylnd** [comment]
Okay, thanks guys. It looks like there were some changes deployed that never made it to master, which is where we got confused. I'll add a little more detail to the README in the hopes of preventing this stuff in the future.

**Comment by ericanaughton** [comment]
Thank you all!

**Pull request closed without merging**
