### PR TITLE
New Site Design

### PR DESCRIPTION
**Pull request by whazzmaster**
:tea:

### CODE REVIEW

**Comment by rylnd** [comment]
The site looks awesome. :+1: 

What does the deploy story look like? Presumably the codekit stuff is all just developer files, and we just want to deploy the final html/css/images?

**Comment by whazzmaster** [comment]
We need to summon @chriscoyier to answer that- I just cut the PR.

**Comment by rylnd** [comment]
Sounds good. Only other comment is that the forms are pretty plain jane (which is probably intentional),  and kinda confusing on mobile, layout-wise.

**Comment by itsthatguy** [comment]
`codekit != codepen`

codekit is and IDE right?

**Comment by itsthatguy** [comment]
IIRC, it does precompiling and stuff for you automagically

**Comment by itsthatguy** [comment]
Ignore my previous comments, I was not informed.

**Comment by itsthatguy** [comment]
This is hosted on heroku, right? This rips out the gulp / and webserver... we'll need something to run the site on heroku

**Comment by chriscoyier** [comment]
1. CodeKit just handles the build stuff for the Sass and JavaScript. Ain't no big deal to switch it over to Gulp if anyone else wants to also work on it and doesn't use CodeKit.
1. I can fix up those Wufoo forms to make them a bit nicer especially on mobile.
1. It doesn't seem like the kind of site that needs Heroku to me. It's totally static and will work fine on GitHub pages.

**Comment by itsthatguy** [comment]
re: 3. Totally, no reason to, other than heroku is already configured (we use free). We can put it wherever.

We're mostly used to working from local dev environments. We all use a pretty similar stack on front-end projects, thus the reason for build tools. But in all honesty, those gulp files are really outdated, and don't reflect our current stack.

Whatever we do, we just need to make sure we can deploy it somewhere ;)

**Comment by itsthatguy** [comment]
@chriscoyier I have a whole new set of build tools for our front-end stuff (way nicer than the janky crap you ripped out before). I've been wanting to add in subtree deploys, which would let us use a subfolder for deploying to gh-pages ... i'd be interested in hooking all of that up, if no one objects?

**Comment by itsthatguy** [comment]
With build tools -> https://github.com/adorableio/ywebca-site/pull/10

**Comment by itsthatguy** [comment]
#10 also adds easy deployment to `gh-pages`.
@chriscoyier @whazzmaster @rylnd please review ...

**Comment by itsthatguy** [comment]
This is awesome, and REALLY appreciated chris!

If we can get a thumbs up on all of the content, we should get this up asap!

**Pull request merged**
